data = [('4:55', 'saturday' , 'green'),
        ('4:55', 'sunday' , 'gray'),
        ('4:55', 'monday' , 'green'),
        ('4:55', 'tuesday' , 'green'),
        ('4:55', 'wednesday' , 'green'),
        ('4:55', 'thursday' , 'green'),
        ('4:55', 'friday' , 'green'),

        ('5:35', 'saturday' , 'green'),
        ('5:35', 'sunday' , 'gray'),
        ('5:35', 'monday' , 'yellow'),
        ('5:35', 'tuesday' , 'green'),
        ('5:35', 'wednesday' , 'green'),
        ('5:35', 'thursday' , 'green'),
        ('5:35', 'friday' , 'green'),

        ('6:25', 'saturday' , 'green'),
        ('6:25', 'sunday' , 'green'),
        ('6:25', 'monday' , 'yellow'),
        ('6:25', 'tuesday' , 'yellow'),
        ('6:25', 'wednesday' , 'green'),
        ('6:25', 'thursday' , 'green'),
        ('6:25', 'friday' , 'green'),

        ('7:05', 'saturday' , 'green'),
        ('7:05', 'sunday' , 'green'),
        ('7:05', 'monday' , 'yellow'),
        ('7:05', 'tuesday' , 'yellow'),
        ('7:05', 'wednesday' , 'yellow'),
        ('7:05', 'thursday' , 'yellow'),
        ('7:05', 'friday' , 'green'),

        ('7:55', 'saturday' , 'green'),
        ('7:55', 'sunday' , 'green'),
        ('7:55', 'monday' , 'yellow'),
        ('7:55', 'tuesday' , 'yellow'),
        ('7:55', 'wednesday' , 'yellow'),
        ('7:55', 'thursday' , 'yellow'),
        ('7:55', 'friday' , 'green'),

        ('8:40', 'saturday' , 'yellow'),
        ('8:40', 'sunday' , 'yellow'),
        ('8:40', 'monday' , 'red'),
        ('8:40', 'tuesday' , 'red'),
        ('8:40', 'wednesday' , 'yellow'),
        ('8:40', 'thursday' , 'yellow'),
        ('8:40', 'friday' , 'green'),

        ('9:40', 'saturday' , 'red'),
        ('9:40', 'sunday' , 'red'),
        ('9:40', 'monday' , 'yellow'),
        ('9:40', 'tuesday' , 'yellow'),
        ('9:40', 'wednesday' , 'yellow'),
        ('9:40', 'thursday' , 'yellow'),
        ('9:40', 'friday' , 'yellow'),

        ('10:25', 'saturday' , 'red'),
        ('10:25', 'sunday' , 'red'),
        ('10:25', 'monday' , 'yellow'),
        ('10:25', 'tuesday' , 'green'),
        ('10:25', 'wednesday' , 'green'),
        ('10:25', 'thursday' , 'green'),
        ('10:25', 'friday' , 'green'),

        ('11:15', 'saturday' , 'red'),
        ('11:15', 'sunday' , 'red'),
        ('11:15', 'monday' , 'green'),
        ('11:15', 'tuesday' , 'green'),
        ('11:15', 'wednesday' , 'green'),
        ('11:15', 'thursday' , 'green'),
        ('11:15', 'friday' , 'green'),

        ('11:55', 'saturday' , 'red'),
        ('11:55', 'sunday' , 'red'),
        ('11:55', 'monday' , 'green'),
        ('11:55', 'tuesday' , 'green'),
        ('11:55', 'wednesday' , 'green'),
        ('11:55', 'thursday' , 'green'),
        ('11:55', 'friday' , 'yellow'),

        ('12:50', 'saturday' , 'yellow'),
        ('12:50', 'sunday' , 'red'),
        ('12:50', 'monday' , 'green'),
        ('12:50', 'tuesday' , 'green'),
        ('12:50', 'wednesday' , 'green'),
        ('12:50', 'thursday' , 'green'),
        ('12:50', 'friday' , 'yellow'),

        ('13:30', 'saturday' , 'yellow'),
        ('13:30', 'sunday' , 'red'),
        ('13:30', 'monday' , 'green'),
        ('13:30', 'tuesday' , 'green'),
        ('13:30', 'wednesday' , 'green'),
        ('13:30', 'thursday' , 'yellow'),
        ('13:30', 'friday' , 'yellow'),

        ('14:30', 'saturday' , 'yellow'),
        ('14:30', 'sunday' , 'red'),
        ('14:30', 'monday' , 'green'),
        ('14:30', 'tuesday' , 'green'),
        ('14:30', 'wednesday' , 'green'),
        ('14:30', 'thursday' , 'yellow'),
        ('14:30', 'friday' , 'yellow'),

        ('15:10', 'saturday' , 'red'),
        ('15:10', 'sunday' , 'red'),
        ('15:10', 'monday' , 'yellow'),
        ('15:10', 'tuesday' , 'green'),
        ('15:10', 'wednesday' , 'green'),
        ('15:10', 'thursday' , 'red'),
        ('15:10', 'friday' , 'red'),

        ('16:00', 'saturday' , 'red'),
        ('16:00', 'sunday' , 'red'),
        ('16:00', 'monday' , 'yellow'),
        ('16:00', 'tuesday' , 'yellow'),
        ('16:00', 'wednesday' , 'yellow'),
        ('16:00', 'thursday' , 'red'),
        ('16:00', 'friday' , 'red'),

        ('16:40', 'saturday' , 'red'),
        ('16:40', 'sunday' , 'red'),
        ('16:40', 'monday' , 'yellow'),
        ('16:40', 'tuesday' , 'yellow'),
        ('16:40', 'wednesday' , 'yellow'),
        ('16:40', 'thursday' , 'red'),
        ('16:40', 'friday' , 'red'),

        ('17:30', 'saturday' , 'red'),
        ('17:30', 'sunday' , 'red'),
        ('17:30', 'monday' , 'yellow'),
        ('17:30', 'tuesday' , 'yellow'),
        ('17:30', 'wednesday' , 'yellow'),
        ('17:30', 'thursday' , 'yellow'),
        ('17:30', 'friday' , 'yellow'),

        ('18:10', 'saturday' , 'red'),
        ('18:10', 'sunday' , 'red'),
        ('18:10', 'monday' , 'green'),
        ('18:10', 'tuesday' , 'green'),
        ('18:10', 'wednesday' , 'green'),
        ('18:10', 'thursday' , 'green'),
        ('18:10', 'friday' , 'yellow'),

        ('19:00', 'saturday' , 'red'),
        ('19:00', 'sunday' , 'red'),
        ('19:00', 'monday' , 'green'),
        ('19:00', 'tuesday' , 'green'),
        ('19:00', 'wednesday' , 'green'),
        ('19:00', 'thursday' , 'green'),
        ('19:00', 'friday' , 'green'),

        ('19:45', 'saturday' , 'red'),
        ('19:45', 'sunday' , 'red'),
        ('19:45', 'monday' , 'green'),
        ('19:45', 'tuesday' , 'green'),
        ('19:45', 'wednesday' , 'green'),
        ('19:45', 'thursday' , 'green'),
        ('19:45', 'friday' , 'green'),

        ('20:20', 'saturday' , 'red'),
        ('20:20', 'sunday' , 'red'),
        ('20:20', 'monday' , 'green'),
        ('20:20', 'tuesday' , 'green'),
        ('20:20', 'wednesday' , 'green'),
        ('20:20', 'thursday' , 'green'),
        ('20:20', 'friday' , 'green'),

        ('21:10', 'saturday' , 'red'),
        ('21:10', 'sunday' , 'red'),
        ('21:10', 'monday' , 'gray'),
        ('21:10', 'tuesday' , 'gray'),
        ('21:10', 'wednesday' , 'gray'),
        ('21:10', 'thursday' , 'gray'),
        ('21:10', 'friday' , 'green'),

        ('21:40', 'saturday' , 'red'),
        ('21:40', 'sunday' , 'red'),
        ('21:40', 'monday' , 'green'),
        ('21:40', 'tuesday' , 'green'),
        ('21:40', 'wednesday' , 'green'),
        ('21:40', 'thursday' , 'green'),
        ('21:40', 'friday' , 'green'),

        ('22:30', 'saturday' , 'gray'),
        ('21:40', 'sunday' , 'red'),
        ('21:40', 'monday' , 'gray'),
        ('21:40', 'tuesday' , 'gray'),
        ('21:40', 'wednesday' , 'gray'),
        ('21:40', 'thursday' , 'gray'),
        ('21:40', 'friday' , 'green'),

        ('23:05', 'saturday' , 'green'),
        ('23:05', 'sunday' , 'green'),
        ('23:05', 'monday' , 'green'),
        ('23:05', 'tuesday' , 'green'),
        ('23:05', 'wednesday' , 'green'),
        ('23:05', 'thursday' , 'green'),
        ('23:05', 'friday' , 'green'),

        ('00:05', 'saturday' , 'gray'),
        ('00:05', 'monday' , 'gray'),
        ('00:05', 'tuesday' , 'gray'),
        ('00:05', 'wednesday' , 'gray'),
        ('00:05', 'thursday' , 'gray'),
        ('00:05', 'friday' , 'green'), ]
